CREATE DATABASE wedding_db;
USE wedding_db;

CREATE TABLE wedding (
`id` INTEGER(10) AUTO_INCREMENT NOT NULL,
`gift_name` VARCHAR(255) NOT NULL,
`reserved` BOOLEAN DEFAULT FALSE NOT NULL,
`date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)


